import type { BodyMeasurements } from '../models/BodyMeasurements';

const now = new Date().toISOString();
const twoWeeksAgo = new Date(Date.now() - 14 * 86400000).toISOString();

export const DEMO_CURRENT: BodyMeasurements = {
  id: crypto.randomUUID(),
  userId: 'demo',
  measureDate: now.slice(0, 10),
  height: 175,
  weight: 74,
  neck: 38,
  shoulderWidth: 44,
  chest: 100,
  waist: 84,
  hip: 97,
  leftUpperArm: 35,
  rightUpperArm: 35.5,
  leftForearm: 28,
  rightForearm: 28.3,
  leftThigh: 57,
  rightThigh: 57.5,
  leftCalf: 38,
  rightCalf: 38.2,
  bodyFat: 16,
  muscleMass: 40,
  waterPercentage: 58,
  visceralFatLevel: 4,
  bmr: 1680,
  boneMass: 3.1,
  createdAt: now,
  updatedAt: now,
};

export const DEMO_PREVIOUS: BodyMeasurements = {
  id: crypto.randomUUID(),
  userId: 'demo',
  measureDate: twoWeeksAgo.slice(0, 10),
  height: 175,
  weight: 76,
  neck: 39,
  shoulderWidth: 43,
  chest: 98,
  waist: 88,
  hip: 98,
  leftUpperArm: 33.5,
  rightUpperArm: 34,
  leftForearm: 27.5,
  rightForearm: 27.8,
  leftThigh: 55.5,
  rightThigh: 56,
  leftCalf: 37,
  rightCalf: 37.3,
  bodyFat: 19,
  muscleMass: 38,
  waterPercentage: 55,
  visceralFatLevel: 6,
  bmr: 1620,
  boneMass: 3.0,
  createdAt: twoWeeksAgo,
  updatedAt: twoWeeksAgo,
};

export const DEMO_SLIM: BodyMeasurements = {
  id: crypto.randomUUID(),
  userId: 'demo-slim',
  measureDate: now.slice(0, 10),
  height: 168,
  weight: 55,
  neck: 32,
  shoulderWidth: 37,
  chest: 82,
  waist: 64,
  hip: 86,
  leftUpperArm: 24,
  rightUpperArm: 24,
  leftForearm: 21,
  rightForearm: 21,
  leftThigh: 46,
  rightThigh: 46,
  leftCalf: 32,
  rightCalf: 32,
  bodyFat: 22,
  muscleMass: 28,
  waterPercentage: 52,
  visceralFatLevel: 3,
  bmr: 1280,
  boneMass: 2.4,
  createdAt: now,
  updatedAt: now,
};

export const DEMO_MUSCULAR: BodyMeasurements = {
  id: crypto.randomUUID(),
  userId: 'demo-muscular',
  measureDate: now.slice(0, 10),
  height: 182,
  weight: 90,
  neck: 42,
  shoulderWidth: 50,
  chest: 115,
  waist: 82,
  hip: 100,
  leftUpperArm: 40,
  rightUpperArm: 40,
  leftForearm: 32,
  rightForearm: 32,
  leftThigh: 64,
  rightThigh: 64,
  leftCalf: 42,
  rightCalf: 42,
  bodyFat: 12,
  muscleMass: 52,
  waterPercentage: 62,
  visceralFatLevel: 2,
  bmr: 2100,
  boneMass: 3.5,
  createdAt: now,
  updatedAt: now,
};

// 添加女性 demo 数据
export const DEMO_CURRENT_FEMALE: BodyMeasurements = {
  id: crypto.randomUUID(),
  userId: 'demo-female',
  measureDate: now.slice(0, 10),
  height: 162,
  weight: 56,
  neck: 33,
  shoulderWidth: 38,
  chest: 88,
  waist: 70,
  hip: 92,
  leftUpperArm: 27,
  rightUpperArm: 27.2,
  leftForearm: 23,
  rightForearm: 23.1,
  leftThigh: 52,
  rightThigh: 52.3,
  leftCalf: 34,
  rightCalf: 34.1,
  bodyFat: 22,
  muscleMass: 30,
  waterPercentage: 53,
  visceralFatLevel: 4,
  bmr: 1250,
  boneMass: 2.4,
  createdAt: now,
  updatedAt: now,
};

export const DEMO_FIT_FEMALE: BodyMeasurements = {
  id: crypto.randomUUID(),
  userId: 'demo-fit-female',
  measureDate: now.slice(0, 10),
  height: 168,
  weight: 60,
  neck: 34,
  shoulderWidth: 40,
  chest: 92,
  waist: 66,
  hip: 94,
  leftUpperArm: 29,
  rightUpperArm: 29.3,
  leftForearm: 24,
  rightForearm: 24.2,
  leftThigh: 54,
  rightThigh: 54.4,
  leftCalf: 35,
  rightCalf: 35.2,
  bodyFat: 19,
  muscleMass: 33,
  waterPercentage: 55,
  visceralFatLevel: 3,
  bmr: 1350,
  boneMass: 2.6,
  createdAt: now,
  updatedAt: now,
};

export const ALL_DEMO_DATA: Record<string, { label: string; data: BodyMeasurements }> = {
  current: { label: '当前数据（男）', data: DEMO_CURRENT },
  slim: { label: '偏瘦体型（男）', data: DEMO_SLIM },
  muscular: { label: '肌肉体型（男）', data: DEMO_MUSCULAR },
  currentFemale: { label: '当前数据（女）', data: DEMO_CURRENT_FEMALE },
  fitFemale: { label: '健身女性', data: DEMO_FIT_FEMALE },
};
