"""add_body_composition_and_daily_metrics_fields

Revision ID: e2c3ad11c3db
Revises: ce5a604012dc
Create Date: 2026-04-22 13:57:10.738174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c3ad11c3db'
down_revision: Union[str, Sequence[str], None] = 'ce5a604012dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_composition_records', sa.Column('muscle_rate', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('bone_mass', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('protein_mass', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('ideal_weight', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('weight_control', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('fat_control', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('muscle_control', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('body_type', sa.String(length=50), nullable=True))
    op.add_column('body_composition_records', sa.Column('nutrition_status', sa.String(length=50), nullable=True))
    op.add_column('body_composition_records', sa.Column('body_age', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('subcutaneous_fat', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('fat_free_mass', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('fat_burn_hr_low', sa.Float(), nullable=True))
    op.add_column('body_composition_records', sa.Column('fat_burn_hr_high', sa.Float(), nullable=True))
    op.add_column('daily_metrics', sa.Column('visceral_fat_level', sa.Float(), nullable=True))
    op.add_column('daily_metrics', sa.Column('bmr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_metrics', 'bmr')
    op.drop_column('daily_metrics', 'visceral_fat_level')
    op.drop_column('body_composition_records', 'fat_burn_hr_high')
    op.drop_column('body_composition_records', 'fat_burn_hr_low')
    op.drop_column('body_composition_records', 'fat_free_mass')
    op.drop_column('body_composition_records', 'subcutaneous_fat')
    op.drop_column('body_composition_records', 'body_age')
    op.drop_column('body_composition_records', 'nutrition_status')
    op.drop_column('body_composition_records', 'body_type')
    op.drop_column('body_composition_records', 'muscle_control')
    op.drop_column('body_composition_records', 'fat_control')
    op.drop_column('body_composition_records', 'weight_control')
    op.drop_column('body_composition_records', 'ideal_weight')
    op.drop_column('body_composition_records', 'protein_mass')
    op.drop_column('body_composition_records', 'bone_mass')
    op.drop_column('body_composition_records', 'muscle_rate')
    # ### end Alembic commands ###
